package com.deysi.battleship.service;

import com.deysi.battleship.exception.InvalidPlacementException;
import com.deysi.battleship.model.Board;
import com.deysi.battleship.model.Coordinate;
import com.deysi.battleship.model.GamePhase;
import com.deysi.battleship.model.GameState;
import com.deysi.battleship.model.Orientation;
import com.deysi.battleship.model.Ship;
import com.deysi.battleship.model.ShipType;
import com.deysi.battleship.model.ShotResult;
import com.deysi.battleship.model.ShotStatus;
import com.deysi.battleship.model.Turn;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Random;

/**
 * Game rules and turn handling.
 */
public class GameEngine {

    private final ShipFactory shipFactory;
    private final ShotStrategy shotStrategy;
    private final Random random = new Random();

    /**
     * Creates a game engine using random machine shots.
     *
     * @param shipFactory ship factory used to create fleet units
     */
    public GameEngine(ShipFactory shipFactory) {
        this(shipFactory, new RandomShotStrategy());
    }

    /**
     * Creates a game engine with explicit machine shot strategy.
     *
     * @param shipFactory ship factory used to create fleet units
     * @param shotStrategy strategy used by the machine to pick next shot
     */
    public GameEngine(ShipFactory shipFactory, ShotStrategy shotStrategy) {
        this.shipFactory = shipFactory;
        this.shotStrategy = shotStrategy;
    }

    /**
     * Creates a fresh game state with random enemy fleet placement.
     *
     * @param nickname player nickname
     * @return new game state
     */
    public GameState newGame(String nickname) {
        Board playerBoard = new Board();
        Board enemyBoard = new Board();
        placeRandomFleet(enemyBoard);
        return new GameState(nickname, playerBoard, enemyBoard);
    }

    /**
     * Auto-places the whole player fleet during placing phase.
     *
     * @param gameState current game state
     */
    public void autoPlacePlayerFleet(GameState gameState) {
        if (gameState.getGamePhase() != GamePhase.PLACING || gameState.getPlayerBoard().isFleetComplete()) {
            return;
        }
        placeRandomFleet(gameState.getPlayerBoard());
    }

    /**
     * Places one player ship at the specified position.
     *
     * @param gameState current game state
     * @param shipType ship type to place
     * @param coordinate origin coordinate
     * @param orientation placement orientation
     * @throws InvalidPlacementException when placement is invalid
     */
    public void placePlayerShip(GameState gameState, ShipType shipType, Coordinate coordinate, Orientation orientation)
            throws InvalidPlacementException {
        if (gameState.getGamePhase() != GamePhase.PLACING) {
            throw new IllegalStateException("Ships can only be placed before the battle starts.");
        }
        Ship ship = shipFactory.create(shipType, coordinate, orientation);
        if (!gameState.getPlayerBoard().canPlaceShip(ship)) {
            throw new InvalidPlacementException("The selected ship cannot be placed there.");
        }
        gameState.getPlayerBoard().placeShip(ship);
    }

    /**
     * Transitions game from placing to playing phase.
     *
     * @param gameState current game state
     */
    public void startBattle(GameState gameState) {
        if (!gameState.getPlayerBoard().isFleetComplete()) {
            throw new IllegalStateException("The player's fleet is not complete.");
        }
        gameState.setGamePhase(GamePhase.PLAYING);
        gameState.setCurrentTurn(Turn.PLAYER);
    }

    /**
     * Applies player's shot to enemy board.
     *
     * @param gameState current game state
     * @param coordinate target coordinate
     * @return shot outcome
     */
    public ShotResult playerShoot(GameState gameState, Coordinate coordinate) {
        ensureTurn(gameState, Turn.PLAYER);
        return applyShot(gameState, gameState.getEnemyBoard(), true, coordinate);
    }

    /**
     * Executes machine turn following configured shot strategy.
     *
     * @param gameState current game state
     * @return last shot result generated by machine in this turn
     */
    public ShotResult performMachineTurn(GameState gameState) {
        ensureTurn(gameState, Turn.MACHINE);
        ShotResult result = null;
        do {
            // La estrategia decide la siguiente coordenada no disparada.
            Coordinate coordinate = shotStrategy.nextShot(gameState.getPlayerBoard());
            result = applyShot(gameState, gameState.getPlayerBoard(), false, coordinate);
            // La maquina repite turno mientras acierta (HIT/SUNK), termina cuando cae al agua.
        } while (result.status() != ShotStatus.WATER && !gameState.isFinished());
        if (!gameState.isFinished()) {
            gameState.setCurrentTurn(Turn.PLAYER);
        }
        return result;
    }

    /**
     * Returns text lines for remaining player fleet by type.
     *
     * @param gameState current game state
     * @return fleet status lines for UI list
     */
    public List<String> getRemainingFleetText(GameState gameState) {
        List<String> fleetTexts = new ArrayList<>();
        for (ShipType shipType : ShipType.values()) {
            int placed = gameState.getPlayerBoard().getPlacedCount(shipType);
            int remaining = shipType.quantity() - placed;
            fleetTexts.add(String.format(Locale.ENGLISH, "%s - remaining: %d/%d", shipType.displayName(), remaining, shipType.quantity()));
        }
        return fleetTexts;
    }

    private ShotResult applyShot(GameState gameState, Board targetBoard, boolean targetEnemy, Coordinate coordinate) {
        try {
            ShotResult result = targetBoard.receiveShot(coordinate);
            if (result.status() == ShotStatus.SUNK) {
                // Lleva estadisticas de hundimientos por bando para UI y persistencia.
                if (targetEnemy) {
                    gameState.incrementPlayerSunkShips();
                } else {
                    gameState.incrementEnemySunkShips();
                }
            }
            if (targetBoard.allShipsSunk()) {
                // Cierre oficial de partida cuando no quedan naves en pie.
                gameState.setGamePhase(GamePhase.FINISHED);
                gameState.setPlayerWinner(targetEnemy);
            }
            // El turno solo cambia cuando el disparo cae al agua.
            gameState.setCurrentTurn(result.status() == ShotStatus.WATER ? gameState.getCurrentTurn().opposite() : gameState.getCurrentTurn());
            return result;
        } catch (InvalidPlacementException exception) {
            throw new IllegalStateException(exception.getMessage(), exception);
        }
    }

    private void placeRandomFleet(Board board) {
        for (ShipType shipType : ShipType.defaultFleet()) {
            boolean placed = false;
            while (!placed) {
                // Intenta posiciones aleatorias hasta hallar una ubicacion valida.
                Orientation orientation = random.nextBoolean() ? Orientation.HORIZONTAL : Orientation.VERTICAL;
                Coordinate origin = new Coordinate(random.nextInt(Board.SIZE), random.nextInt(Board.SIZE));
                Ship ship = shipFactory.create(shipType, origin, orientation);
                if (board.canPlaceShip(ship)) {
                    try {
                        board.placeShip(ship);
                        placed = true;
                    } catch (InvalidPlacementException ignored) {
                        // Validation already confirmed above.
                    }
                }
            }
        }
    }

    private void ensureTurn(GameState gameState, Turn expectedTurn) {
        if (gameState.getGamePhase() != GamePhase.PLAYING) {
            throw new IllegalStateException("The battle has not started yet.");
        }
        if (gameState.getCurrentTurn() != expectedTurn) {
            throw new IllegalStateException("It is not the expected turn.");
        }
    }
}
